### ISSUE TITLE
Japanese error descriptions are given by default

### ISSUE THREAD

**Issue by cbourjau** [tom-tan/auctex-latexmk#18]
Hi,
I just installed this package and noticed that if an error occurs in the compilation and I hit ```C-` ``` the error is give in japanese:

```
ERROR: Undefined control sequence.

--- TeX said ---
<argument> \undefinedpagestyle 
                               
l.38 \pagestyle{fancyplain}
                           
--- HELP ---
TeXが未定義の命令名を発見しました．おそらく入力の誤りでしょう．もしこ
のエラーがLaTeX命令の処理中に生じた場合は，その命令は間違った位置に置か
れています．例えば，リスト環境の中でないのに\item命令が使われた場合など
です．また，\documentclass命令がない場合にもこのエラーが生じます．
```

The only setting I have in my init.el are
```
  (setq auctex-latexmk-inherit-TeX-PDF-mode t)
  (require 'auctex-latexmk)
  (auctex-latexmk-setup)
```

I also tried `(setq japanese-TeX-use-kanji-opt-flag nil)` to no avail. I think this might have something to do with commit ` 0ffeef4` from a few days ago. At least it looks like some settings were changed at this point concerning the encoding?

Any ideas to the origin of this or am I just missing a simple setting somewhere?
Thanks a lot!
Chris

**Comment by tom-tan** [comment]
Thank you for your report!

I revert the commit `0ffeef4` because I didn't notice this issue.
Please check the latest version.

* * *
Here is the reason why this issue happened:

In the commit `0ffeef4`, I added `(require 'tex-jp)` to unify the code for Japanese encoding.
However, it implicitly changes the error message list (`TeX-error-description-list`) if `japanese-TeX-error-messages` is `t`.
To avoid this issue, we should set `japanese-TeX-error-message` to `nil` before requiring `tex-jp` but it requires extra cost for users even if they do not use Japanese encodings.

**Comment by cbourjau** [comment]
Splendid! Thank you very much for the quick reply. Everything works as expected now. And also thank for this package!
